# vim: ft=yaml

tunnel:
  - address: inet0.tonesoft.com
    domain: tonesoft.com
    user: gfb
    interface: en0
    identity: ~/.ssh/id_rsa
    ipblock: !ruby/range 30..50
    host:
      - address: sesys5
        port: [ 80, 8080 ]
      - address: moose
        port: [ 80, 2500, 22, 23, 139 ]
      - address: bear
        port: [ 22 ]
      - address: titan
        port: [ 22 ]
      - address: oz
        port: [ 80, 22 ]
      - address: ant
        port: [ 80 ]
      - address: mule
        port: [ 22, 5900, 4711, 139 ]
      - address: gfbs
        port: [ 22, 80, 3000 ]
      - address: bison
        port: [ 22, 80 ]
      - address: gfb
        port: [ 139 ]
      - address: ayss
        port: [ 22, 80 ]
      - address: mvs
        port: [ 22, 23, 80 ]
