#!/usr/bin/env ruby
=begin
  vim: sw=2:
  Copyright (c) 2014, Gennady Bystritsky <bystr@mac.com>

  Distributed under the MIT Licence.
  This is free software. See 'LICENSE' for details.
  You must read and accept the license prior to use.

  Author: Gennady Bystritsky
=end

$:.concat ENV.to_hash['PATH'].to_s.split(File::PATH_SEPARATOR)

require 'tsc/application'

class Application < TSC::Application
  in_generator_context do |_content|
    _content << '#!' + figure_ruby_path
    _content << ''

    _content << '$:.unshift ' + 'File.dirname(__FILE__)'
    _content << '$:.unshift ' + File.dirname(figure_ruby_path).inspect
    _content << ''

    _content << 'PLATFORM_TOP = ' + self.class.installation_parameters[:platform_top].inspect
    _content << 'PROJECTS_TOP = ' + self.class.installation_parameters[:projects_top].inspect

    _content << 'APP_TOP = ' + self.class.installation_top.inspect
    _content << 'APP_BASE = ' + self.class.installation_parameters[:app_base].inspect
    _content << 'APP_VERSION = ' + self.class.installation_parameters[:app_version].inspect
    _content << ''

    _content << IO.readlines(__FILE__).slice(1..-1)
  end

  def start
    handle_errors do
      require 'pathname'
      require 'tsc/path'

      process_command_line figure_command_line(script_name, ARGV)
    end
  end

  def config
    @config ||= yaml_config.data
  end

  def config_location
    @config_location ||= Pathname.new(yaml_config.locations.first)
  end

  def app_top
    @app_top ||= begin
      if defined? APP_TOP
        Pathname.new(APP_TOP)
      else
        script_real_location.parent
      end
    end
  end

  def app_bin
    @app_bin ||= script_real_location
  end

  def app_hooks
    @app_hooks ||= begin
      if defined? APP_TOP
        app_bin.join('hooks')
      else
        system_path.entries.select { |_entry|
          _entry.include? '/runtime/'
        }
      end
    end
  end

  def app_version
    @app_version ||= defined?(APP_VERSION) ? APP_VERSION : 'not defined'
  end

  def app_base
    @app_base ||= defined?(APP_BASE) ? APP_BASE : 'app'
  end

  def app_env_path
    @app_env_path ||= TSC::Path[env.path].load
  end

  def project_env_path
    @project_env_path ||= TSC::Path[env.project_path].load
  end

  def system_path
    @system_path ||= TSC::PATH.new.load
  end

  def system_lib_path
    @system_lib_path ||= TSC::Path['LD_LIBRARY_PATH:SHLIB_PATH:LIBPATH'].load
  end

  def env
    @env ||= Env.new self
  end

  def interpolator
    @interpolator ||= Interpolator.new self
  end

  def defaults
    @defaults ||= config.properties('defaults')
  end

  def project_settings
    @project_settings ||= config.properties('project-settings')
  end

  def with_projects_top
    yield Pathname.new(PROJECTS_TOP) if defined? PROJECTS_TOP
  end

  private
  #######

  class Servant
    attr_reader :master

    def initialize(master)
      @master = master
    end
  end

  class Env < Servant
    def names
      @names ||= {}
    end

    def base
      @base ||= normalize(master.app_base)
    end

    def main
      @main ||= name master.app_base
    end

    def build
      @build ||= join base, 'B'
    end

    def path
      @path ||= join base, 'E', 'PATH'
    end

    def project_path
      @project_path ||= join base, 'E', 'PROJECT', 'PATH'
    end

    def ignore_projects?
      [ 'yes', 'true' ].include? ENV[join(base, 'B', 'IGNORE', 'PROJECTS')]
    end

    def ignore_facilities?
      [ 'yes', 'true' ].include? ENV[join(base, 'B', 'IGNORE', 'FACILITIES')]
    end

    def unless_build
      return if ENV[build] == 'off'

      begin
        yield
      ensure
        ENV[build] = 'off'
      end
    end

    def name(facility)
      names[facility] ||= join base, 'V', (facility == master.app_base ? nil : normalize(facility))
    end

    def with_value_for(facility)
      name(facility).tap do |_name|
        ENV[_name].tap do |_value|
          next if [ nil, '', 'on', 'off' ].include? _value
          yield _value

          ENV[_name] = 'off'
        end
      end
    end

    private
    #######

    def normalize(item)
      item.to_s.split(%r{[_-]}).map(&:strip).reject(&:empty?).map(&:upcase)
    end

    def join(*args)
      args.flatten.compact.join('_')
    end
  end

  class Interpolator < Servant
    def make(value)
      value.to_s.gsub(%r{%[{](\w+)[}]}) { |_match|
        ENV[$1] || master.defaults.fetch($1, nil) or raise "#{$1}: Not in environment or default"
      }
    end
  end

  class Project < Servant
    attr_reader :name, :default_version

    def initialize(master, name, default_version)
      super master

      @name = name
      @default_version = default_version.tap { |_version|
        break _version.to_s if _version
      }
    end

    def setup
      [].tap do |_locations|
        unless import_script_folders.empty?
          return master.project_env_path.front import_script_folders
        end

        _locations.concat import_roots

        master.with_projects_top do |_top|
          _top.join(name, version, 'bin').tap do |_folder|
            return master.project_env_path.front _folder if _folder.directory?
          end

          _locations << _top
        end

        "Project #{name.inspect} of version #{version.inspect} not available".tap do |_message|
          raise _message if _locations.empty?

          TSC::Error.persist do |_actions|
            _locations.each do |_location|
              _actions.add {
                raise _message + ' in ' + _location.to_s
              }
            end
          end
        end
      end

    end

    def import_roots
      @import_roots ||= [].tap { |_roots|
        param('import-root').split(':').each do |_item|
          _item.strip.tap do |_item|
            _roots << Pathname.new(_item).expand_path(master.config_location) unless _item.empty?
          end
        end
      }
    end

    def import_script_folders
      @import_script_folders ||= [].tap { |_folders|
        import_roots.each do |_root|
          _root.join(name, version, 'scripts').tap do |_folder|
            _folders << _folder if _folder.directory?
          end
        end
      }
    end

    def version
      @version ||= begin
        catch :version do
          master.env.with_value_for name do |_value|
            throw :version, _value
          end

          default_version or raise "No version for project #{name.inspect} provided"
        end
      end
    end

    private
    #######

    def param(name)
      master.interpolator.make master.project_settings.fetch(name, '')
    end
  end

  def make_folder(top, *components)
    Pathname.new(top).join components.join('-')
  end

  def projects
    @projects ||= {}
  end

  def facilities
    @facilities ||= {}
  end

  def ensure_folder_exists(folder)
    raise "No #{folder}" unless folder.exist?
    folder
  end

  def validate_and_setup_projects
    TSC::Error.persist do |_actions|
      projects.values.each do |_project|
        _actions.add {
          _project.setup
        }
      end
    end
  end

  def validate_and_setup_facilities
    TSC::Error.persist do |_actions|
      facilities.each do |_item, _version|
        platform_top([ _item, _version ].join('-')).tap do |_folder|
          _actions.add {
            app_env_path.front ensure_folder_exists(_folder)
          }
        end
      end
    end
  end

  def request_app_version(version)
    request_project app_base, version
  end

  def request_project(name, version)
    projects[name] ||= Project.new(self, name, version)
  end

  def request_facility(facility, version)
    if facility == app_base
      request_app_version version
    else
      facilities[facility] ||= version
    end
  end

  def update_from_environment(facility)
    env.with_value_for facility do |_version|
      request_facility facility, _version
    end
  end

  def update_from_config
    env.unless_build do
      unless env.ignore_facilities?
        config.properties('apps').each do |_app, _version|
          request_facility _app, _version
        end
      end

      unless env.ignore_projects?
        config.properties('projects').each do |_project, _version|
          request_project _project, _version
        end

        config.fetch 'version' do |_version|
          request_app_version _version
        end
      end
    end
  end

  def yaml_config
    @yaml_config ||= begin
      require 'sk/yaml-config'

      SK::YamlConfig[config_locator("config/#{app_base}.yaml")]
    end
  end

  def config_locator(file)
    require 'sk/config/uproot-locator'
    require 'sk/config/spot-locator'

    SK::Config::UprootLocator.new :item => file, :spot => '.', :locator => begin
      if defined?(APP_VERSION)
        SK::Config::SpotLocator.new :item => file, :spot => app_top
      end
    end
  end

  def process_command_line(args)
    until args.empty? or args.first.index('--') != 0
      case args.first
        when '--validate'
          ENV[env.main].tap do |_value|
            next if [ nil, '', 'on', 'off' ].include? _value
            next if app_version == _value

            raise "Version mismatch: #{app_version} instead of required #{_value}"
          end

        when '--report'
          puts "#{script_real_name}: Current version: #{app_version}"
          @info = true

        else
          raise "Unsuported option: #{args.first}"
      end

      args.shift
    end

    env.with_value_for app_base do |_version|
      request_app_version _version
    end

    launch *(args.empty? ? 'env' : args) do |_command, _args|
      update_from_environment _command
      update_from_config

      validate_and_setup_facilities
      validate_and_setup_projects

      print_info script_real_location.parent, app_env_path.entries

      system_lib_path.front(platform_top, app_env_path.entries.reverse) { |_entry|
        [ _entry.join('lib'), _entry.join('lib64') ]
      }
      system_path.front app_bin
      system_path.front project_env_path.entries.reverse

      system_path.front(platform_top, app_env_path.entries.reverse) { |_entry|
        _entry.join('bin')
      }
      system_path.front app_hooks
    end
  end

  def launch(command, *args)
    yield command, args

    system_path.find_all(command).each do |_item|
      Pathname.new(_item).realpath.tap do |_path|
        next if _path == script_real_location.join(script_name)
        next if _path == app_bin.join(script_name)

        app_env_path.install
        project_env_path.install
        system_lib_path.install
        system_path.install

        exec _item, *args
      end
    end

    raise "Command not found: #{command}"
  end

  def print_info(*args)
    return unless @info
    args.flatten.compact.each do |_item|
      puts "INFO: #{_item}"
    end
  end

  def exec(*args)
    puts "### #{args.join(' ')}" if verbose?
    Kernel.exec *args
  end

  def figure_command_line(name, args)
    case name
      when %r{^(.+)-env$}
        scan_for_versioned_facilities scan_for_version($1, args)

      else
        [ name, *args ]
    end
  end

  def scan_for_versioned_facilities(items)
    until items.empty?
      break unless items.first =~ %r{^(.+?)-(.+)$}
      break unless scan_for_version($1, [ $2 ]).empty?

      items.shift
    end

    items
  end

  def scan_for_version(facility, items)
    until items.empty?
      break unless items.first =~ %r{^\d+([.]\d+)+(([a-z])|(-p\d+))?$}
      request_facility facility, items.shift
    end

    items
  end

  def platform_top(*args)
    (@platform_top ||= figure_platform_top).join *args
  end

  def figure_platform_top
    return Pathname.new(PLATFORM_TOP) if defined? PLATFORM_TOP

    TSC::Error.wrap_with 'Platform top cannot be determined' do
      case find_in_path('ruby').first
        when nil
          raise 'No ruby'

        when %r{^(.+/platform/.+?)(/ruby-\d+([.]\d+)+)?(-p\d+)?/bin/ruby$}
          return Pathname.new($1)

        else
          raise 'No platform bound ruby'
      end
    end
  end
end

Application.new.start
