#!/bin/ksh
# vi: sw=2:

OPTERR=0
unset selector
selector="-name *.[MmCcHh]*"
grep_options=""

set -o noglob

while getopts "viqan:" option; do
  case "${option}" in
    v)
      set -xv
    ;;
    q)
      grep_options="${grep_options} -q"
    ;;
    i)
      grep_options="${grep_options} -i"
    ;;
    a)
      unset selector
    ;;
    n)
      [ "${selector:+set}" = set ] && {
        selector="${selector} -o "
      }
      selector="${selector}-name ${OPTARG}"
    ;;
    *)
      echo "USAGE `basename ${0}` [-d<folder>] [<svn command>]" 1>&2
      exit 2
    ;;
  esac
done
shift `expr "${OPTIND}" - 1`

[ "${#}" -eq 0 ] && {
  echo "USAGE: `basename ${0}` <location> [ <pattern> [ <extra find options> ...] ]"
  exit 2
}
location="${1}"
pattern="${2}"

[ "${#}" -ne 0 ] && shift
[ "${#}" -ne 0 ] && shift

if [ "${pattern:+set}" = set ]; then
  exec find ${location:-.} -follow -name .svn -prune -o -type f ${selector} -exec grep ${grep_options} -- "${pattern}" "{}" \; "${@:--print}"
else
  exec find ${location:-.} -follow -name .svn -prune -o -type f ${selector} "${@:--print}"
fi
