#!/bin/ksh
# vi: sw=2:

OPTERR=0
unset SELECTOR ALL
grep_options=""

set -o noglob

while getopts "viqan:" option; do
  case "${option}" in
    v)
      set -xv
    ;;
    q)
      grep_options="${grep_options} -q"
    ;;
    i)
      grep_options="${grep_options} -i"
    ;;
    a)
      ALL=true
    ;;
    n)
      [ "${SELECTOR:+set}" = set ] && {
        SELECTOR="${SELECTOR} -o "
      }
      SELECTOR="${SELECTOR}-name ${OPTARG}"
    ;;
    *)
      echo "USAGE `basename ${0}` [-d<folder>] [<svn command>]" 1>&2
      exit 2
    ;;
  esac
done
shift `expr "${OPTIND}" - 1`

[ "${#}" -eq 0 ] && {
  echo "USAGE: `basename ${0}` <location> [ <pattern> [ <extra find options> ...] ]"
  exit 2
}
location="${1}"
pattern="${2}"

[ "${#}" -ne 0 ] && shift
[ "${#}" -ne 0 ] && shift

: ${SELECTOR:="-name *.[MmCcHh]*"}

[ "${ALL}" = true ] && unset SELECTOR

if [ "${pattern:+set}" = set ]; then
  exec find ${location:-.} -follow \( -name .svn -o -name CVS -o -name .git \) -prune -o -type f ${SELECTOR} -exec grep ${grep_options} -- "${pattern}" "{}" \; "${@:--print}"
else
  exec find ${location:-.} -follow \( -name .svn -o -name CVS -o -name .git \) -prune -o -type f ${SELECTOR} "${@:--print}"
fi
