#!/bin/sh
# vim: sw=2:
#
#  Copyright (c) 2008, Gennady Bystritsky <bystr@mac.com>
#  
#  Distributed under the MIT Licence.
#  This is free software. See 'LICENSE' for details.
#  You must read and accept the license prior to use.
#  
#  Author: Gennady Bystritsky (gennady.bystritsky@quest.com)

main()
{
  locate_ruby "${@}" "${HOME}"/local/*/bin "${PATH}" /usr/local/bin /usr/bin
}

locate_ruby()
{
  for path in "${@}"; do
    ifs=${IFS}
    IFS=":"
    set -- entry ${path}
    shift

    for directory in "${@}"; do
      program="${directory}/ruby"
      [ "`${program} -rubygems -e 'puts %q{HELLO}'`" = 'HELLO' ] && {
        echo ${program}
        return 0
      }
    done

    IFS=${ifs}
  done 2>/dev/null
}

main "${@}"
