#!/bin/ksh

unset FOLDERS 
OPTERR=0

while getopts "vd:" option; do
  case "${option}" in
    v)
      set -xv
      XARGS_OPTIONS="-t"
    ;;
    d)
      FOLDERS="${FOLDERS:+${FOLDERS} }${OPTARG}"
    ;;
    *)
      echo "USAGE `basename ${0}` [-v] [[-d<folder>] ...] [<svn command>]" 1>&2
      exit 2
    ;;
  esac
done
shift $(( ${OPTIND} - 1 ))

find ${FOLDERS:-.} -name src -prune -exec sh -c 'test -d $0/.svn' {} \; -print | xargs ${XARGS_OPTIONS} -n1 svn "${@:-status}"
