#!/bin/sh
# vim: set sw=2:
# [Do not remove this line, replaced when installed]
# [Do not remove this line, replaced when installed]
#
#  Copyright (c) 2008, Gennady Bystritsky <bystr@mac.com>
#  
#  Distributed under the MIT Licence.
#  This is free software. See 'LICENSE' for details.
#  You must read and accept the license prior to use.
#  
#  Author: Gennady Bystritsky (gennady.bystritsky@quest.com)

SOURCE=__FILE__
eval <<'RUBY'
  require 'tsc/application.rb'
  require 'tsc/path.rb'

  class Application < TSC::Application
    in_generator_context do |_content|
      _content << IO.readlines(SOURCE).slice(0, 2)

      _content << 'PATH="' + File.dirname(figure_ruby_path) + ':${PATH}" export PATH'
      _content << 'RUBY=' + figure_ruby_path.inspect

      _content << IO.readlines(SOURCE).slice(4..-1)
    end
  end
RUBY
__END__() {
  true
}
__END__

main()
{
  : ${RUBY:=ruby}

  [ "${RUBY:+set}" != set ] && {
    echo "Ruby not found" 1>&2
    exit 3
  }
  "${RUBY}" -I"${PATH}" -r tsc/application -e '
    TSC::Application.new.start { 
      require "rubygems"
      require "tsc/platform"

      puts TSC::Platform.current.name 
    }
  '
}

main "${@}"
