#!/bin/sh
# vim: set sw=2:
#
#  Copyright (c) 2008, Gennady Bystritsky <bystr@mac.com>
#  
#  Distributed under the MIT Licence.
#  This is free software. See 'LICENSE' for details.
#  You must read and accept the license prior to use.
#  
#  Author: Gennady Bystritsky (gennady.bystritsky@quest.com)

main()
{
  RUBY=`locate-ruby`
  [ "${RUBY:+set}" != set ] && {
    echo "Ruby not found" 1>&2
    exit 3
  }
  "${RUBY}" -I"${PATH}" -r tsc/application -r tsc/platform -e '
    TSC::Application.new.start { 
      puts TSC::Platform.current.name 
    }
  '
}

main "${@}"
